apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
  finalizers: []
spec:
  destination:
    name: ''
    namespace: monitoring
    server: 'https://xxx.xxx.xxx.xxx:6443'
  source:
    path: monitoring
    repoURL: 'git@github.com:SeboKnt/hf-test-cluster.git'
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
