apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  finalizers: []
spec:
  destination:
    name: ''
    namespace: cert-manager
    server: 'https://xxx.xxx.xxx.xxx:6443'
  source:
    path: cert-manager
    repoURL: 'git@github.com:SeboKnt/hf-test-cluster.git'
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
