apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: cluster-issuer
  namespace: flux-system
spec:
  dependsOn:
    - name: cert-manager
      namespace: cert-manager
      condition: Ready
  resources:
    - cluster-issuer.yaml