---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: backend-tls-secret
  namespace: hobbyfarm-system
spec:
  secretName: backend-tls-secret
  issuerRef:
    kind: ClusterIssuer
    name: production
  commonName: api.k.youngandhungry.org
  dnsNames:
  - api.k.youngandhungry.org
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: admin-tls-secret
  namespace: hobbyfarm-system
spec:
  secretName: admin-tls-secret
  issuerRef:
    kind: ClusterIssuer
    name: production
  commonName: admin.k.youngandhungry.org
  dnsNames:
  - admin.k.youngandhungry.org
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: shell-tls-secret
  namespace: hobbyfarm-system
spec:
  secretName: shell-tls-secret
  issuerRef:
    kind: ClusterIssuer
    name: production
  commonName: shell.k.youngandhungry.org
  dnsNames:
  - shell.k.youngandhungry.org
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ui-tls-secret
  namespace: hobbyfarm-system
spec:
  secretName: ui-tls-secret
  issuerRef:
    kind: ClusterIssuer
    name: production
  commonName: learn.k.youngandhungry.org
  dnsNames:
  - learn.k.youngandhungry.org