apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/hobbyfarm/helm.yaml
patches:
  - path: values.yaml
    target:
      kind: HelmRelease 
      version: v1 
      name: hobbyfarm 
      namespace: hobbyfarm-system 