---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: hobbyfarm
  namespace: flux-system
spec:
  interval: 5m
  path: "./"
  prune: true
  dependsOn:
    - name: base-hobbyfarm
  resources:
    - hcloud.yaml
    - rbac.yaml