apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    rbac.hobbyfarm.io/managed: "true"
  name: hobbyfarm-admin
  namespace: hobbyfarm-system
rules:
- apiGroups:
  - hobbyfarm.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - '*'
  verbs:
  - '*'