---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-tls-secret
  namespace: monitoring
spec:
  secretName: grafanas-tls-secret
  issuerRef:
    kind: ClusterIssuer
    name: production
  commonName: grafana.k.youngandhungry.org
  dnsNames:
  - grafana.k.youngandhungry.org