---
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: base-apps
  namespace: flux-system
spec:
  interval: 5m
  path: ./apps/base/hobbyfarm
  prune: true
  sourceRef:
    kind: GitRepository
    name: repo
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: production-apps
  namespace: flux-system
spec:
  dependsOn:
    - name: base-apps
  interval: 5m
  path: ./apps/production/hobbyfarm
  prune: true
  sourceRef:
    kind: GitRepository
    name: repo