---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: repo
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./clusters/production
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: repo
  timeout: 3m0s
  wait: true