---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: base-infrastructure
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster
  interval: 5m
  path: ./infrastructure/base
  prune: true
  sourceRef:
    kind: GitRepository
    name: repo
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: production-infrastructure
  namespace: flux-system
spec:
  dependsOn:
    - name: base-infrastructure
  interval: 5m
  path: ./infrastructure/production/
  prune: true
  sourceRef:
    kind: GitRepository
    name: repo