apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-system/flux-bootstrap.yaml
  - flux-system/flux-helm.yaml
  - flux-system/flux-kustomization.yaml
  - flux-system/flux-namespace.yaml
  - flux-system/flux-s3-sealed-secret.yaml
  - rbac/developer-role.yaml
  - rbac/developer-rolebinding.yaml
  - rbac/hf-namespace.yaml
  - rbac/owner-clusterrole.yaml
  - rbac/owner-clusterrolebinding.yaml
  - sealed-secret/sealed-secret-helm.yaml
  - sealed-secret/hcloud-token-sealed.yaml
  - apps.yaml
  - infrastructure.yaml