apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-bootstrap.yaml
  - flux-helm.yaml
  - flux-kustomization.yaml
  - flux-namespace.yaml
  - sealed-secret-helm.yaml
  - clusters/production
  - ../../apps/production
  - ../../infrastructure/production

# Please note: file is called recursive