apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - apps.yaml
  - flux-bootstrap.yaml
  - flux-helm.yaml
  - flux-kustomization.yaml
  - flux-namespace.yaml
  - infrastructure.yaml
  - sealed-secret-helm.yaml