apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../clusters/production/flux-bootstrap.yaml
  - ../../clusters/production/flux-helm.yaml
  - ../../clusters/production/flux-kustomization.yaml
  - ../../clusters/production/flux-namespace.yaml
  - ../../clusters/production/sealed-secret-helm.yaml

# Please note: file is called recursive