---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 1h
  chart:
    spec:
      chart: traefik
      version: 'v10.3.4'
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    globalArguments:
      - "--global.checknewversion"
      - "--global.sendanonymoususage"
    ports:
      traefik:
        expose: true
      web:
        expose: true
      websecure:
        expose: true
    additionalArguments:
      - "--providers.kubernetesingress"
      - "--providers.kubernetesingress.ingressclass=traefik"
    service:
      type: LoadBalancer