---
apiVersion: v1
kind: Service
metadata:
  name: tls-demo
  namespace: tls-demo
  labels:
    app.kubernetes.io/name: tls-demo
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: tls-demo
