---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prometheus-tls-secret
  namespace: monitoring
spec:
  secretName: prometheus-tls-secret
  issuerRef:
    kind: ClusterIssuer
    name: production
  commonName: prometheus.k.youngandhungry.org
  dnsNames:
  - prometheus.k.youngandhungry.org