apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k10
  finalizers: []
spec:
  destination:
    name: ''
    namespace: kasten-io
    server: 'https://94.130.177.45:6443'
  source:
    path: k10
    repoURL: 'git@github.com:SeboKnt/hf-test-cluster.git'
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
