apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: developer-rolebinding
  namespace: hobbyfarm-system
subjects:
- kind: User
  name: developer
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: developer-role
  apiGroup: rbac.authorization.k8s.io


# hier muss du noch fixen, dass das rbac nicht erstellt werden kann, 
# solange kein hobbyfarm-system namespace existiert