---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hccm
  namespace: kube-system
spec:
  interval: 1h
  chart:
    spec:
      chart: hccm
      version: '1.19.0'
      sourceRef:
        kind: HelmRepository
        name: hcloud
        namespace: flux-system